=== sewellstephens/late/apps/www/public/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "style": {
      "type": "string",
      "enum": ["default"]
    },
    "tailwind": {
      "type": "object",
      "properties": {
        "config": {
          "type": "string"
        },
        "css": {
          "type": "string"
        },
        "baseColor": {
          "type": "string"
        },
        "cssVariables": {
          "type": "boolean"
        },
        "prefix": {
          "type": "string"
        }
      },
      "required": ["config", "css", "baseColor", "cssVariables"]
    },
    "rsc": {
      "type": "boolean"
    },
    "aliases": {
      "type": "object",
      "properties": {
        "components": {
          "type": "string"
        },
        "ui": {
          "type": "string"
        },
        "plate-ui": {
          "type": "string"
        }
      },
      "required": ["components"]
    }
  },
  "required": ["style", "tailwind", "rsc", "aliases"]
}

=== sewellstephens/late/templates/plate-playground-template/components.json
{
  "$schema": "https://sewellstephens.github.io/late/schema.json",
  "style": "default",
  "rsc": true,
  "tailwind": {
    "config": "tailwind.config.js",
    "css": "src/styles/globals.css",
    "baseColor": "slate",
    "cssVariables": true
  },
  "aliases": {
    "components": "@/components"
  }
}
